steps:
  - name: 'hashicorp/terraform:1.6.6'
    id: Terraform Init
    entrypoint: sh
    args:
      - '-c'
      - |
        cd terraform
        terraform init

  - name: 'hashicorp/terraform:1.6.6'
    id: Terraform Import
    entrypoint: sh
    args:
      - '-c'
      - |
        cd terraform
        terraform import google_bigquery_dataset.realtime_dataset realtime-data-pipeline-123:realtime_dataset
        terraform import google_pubsub_topic.stream_topic realtime-stream-topic
        terraform import google_storage_bucket.staging_bucket realtime-data-pipeline-123-staging
        terraform import google_storage_bucket.raw_data_bucket realtime-data-pipeline-123-raw-data

  - name: 'hashicorp/terraform:1.6.6'
    id: Terraform Plan
    entrypoint: sh
    args:
      - '-c'
      - |
        cd terraform
        terraform plan

  - name: 'hashicorp/terraform:1.6.6'
    id: Terraform Apply
    entrypoint: sh
    args:
      - '-c'
      - |
        cd terraform
        terraform apply -auto-approve

options:
  logging: CLOUD_LOGGING_ONLY
